# GoNude core primitives
# Do not edit this file to add domain-specific nodes — use extensions/ instead.

# Metadata used by scripts/introspect.nu for canvas display and agent use.
# Keys match the short name (strip "prim-", replace "-" with "_").
export const PRIMITIVE_META = {
    fetch:         {category: "input",     color: "#f97316", wirable: [],               agent_hint: "Fetch JSON/table data from a URL via HTTP GET", param_options: {}}
    const:         {category: "input",     color: "#f97316", wirable: [],               agent_hint: "Provide a fixed NUON constant value (e.g. 42, \"hello\", [1 2 3])", param_options: {}}
    env:           {category: "input",     color: "#f97316", wirable: [],               agent_hint: "Read an environment variable by name, returns its string value", param_options: {}}
    file_in:       {category: "input",     color: "#f97316", wirable: [],               agent_hint: "Read a file — auto-detects CSV/JSON/NUON, else returns raw string", param_options: {}}
    ls:            {category: "file",      color: "#f97316", wirable: [],               agent_hint: "List directory contents as a table (name, type, size, modified)", param_options: {}}
    rm:            {category: "file",      color: "#f97316", wirable: [],               agent_hint: "Remove a file at the given path", param_options: {}}
    mkdir:         {category: "file",      color: "#f97316", wirable: [],               agent_hint: "Create a directory (and parents) at the given path", param_options: {}}
    date_now:      {category: "datetime",  color: "#06b6d4", wirable: [],               agent_hint: "Return the current date and time as a datetime value", param_options: {}}
    date_add:      {category: "datetime",  color: "#06b6d4", wirable: [],               agent_hint: "Add a duration to a datetime. amount examples: 1day, 2hr, 30min, -7day", param_options: {}}
    to_timezone:   {category: "datetime",  color: "#06b6d4", wirable: [],               agent_hint: "Convert datetime to a different timezone", param_options: {}}
    list_timezone: {category: "datetime",  color: "#06b6d4", wirable: [],               agent_hint: "List available timezone names", param_options: {}}
    into_filesize: {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Convert a string like 5MB into a filesize value", param_options: {}}
    into_duration: {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Convert a string like 1hr 30min into a duration value", param_options: {}}
    filter:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Filter table rows: pick column, op (>, <, ==, !=, contains), and value"
                   param_options: {op: ["==", "!=", ">", "<", "contains"]}}
    map:           {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Add or replace a column with a NUON constant value", param_options: {}}
    select:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Keep only the named columns from a table (space-separated)", param_options: {}}
    sort:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Sort a table by a column. direction: asc or desc"
                   param_options: {direction: ["asc", "desc"]}}
    count:         {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Count the number of rows in a table", param_options: {}}
    first:         {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Return the first N rows of a table", param_options: {}}
    last:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Return the last N rows of a table", param_options: {}}
    rename:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Rename a column: provide old and new column name", param_options: {}}
    get:           {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Get a field from a record or an index from a list", param_options: {}}
    merge:         {category: "transform", color: "#3b82f6", wirable: ["with"],         agent_hint: "Merge a NUON record into the input record — overlapping keys overwritten. Wire a record to --with for multi-input.", param_options: {}}
    reject:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Remove named columns from a table or record (space-separated)", param_options: {}}
    update:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Update a field in a record/table with a NUON value", param_options: {}}
    group_by:      {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Group table rows by a column — returns a record keyed by the column values", param_options: {}}
    reduce:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Reduce a list to a single value: sum, product, min, max, avg, or join"
                   param_options: {op: ["sum", "product", "min", "max", "avg", "join"]}}
    uniq:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Return unique values from a list (deduplicate)", param_options: {}}
    append:        {category: "transform", color: "#3b82f6", wirable: ["items"],        agent_hint: "Append to a list. Wire a second list/value to --items for multi-input.", param_options: {}}
    flatten:       {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Flatten one level of nesting from a list of lists", param_options: {}}
    reverse:       {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Reverse a list or table", param_options: {}}
    drop:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Skip the first N rows/elements from a list or table", param_options: {}}
    enumerate:     {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Add a zero-based index field to each element — returns [{index, value}, ...]", param_options: {}}
    wrap:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Wrap a single value into a one-element list", param_options: {}}
    join:          {category: "transform", color: "#3b82f6", wirable: ["right"],        agent_hint: "SQL-style join two tables on a shared column. Wire second table to --right port."
                   param_options: {type: ["inner", "left"]}}
    table_concat:  {category: "transform", color: "#3b82f6", wirable: ["more"],         agent_hint: "Vertically stack two tables (UNION ALL). Wire the second table to --more port.", param_options: {}}
    insert_row:    {category: "transform", color: "#3b82f6", wirable: ["row"],          agent_hint: "Append a record as a new row to a table. Wire a record source to --row port.", param_options: {}}
    col_to_list:   {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Extract a single column from a table as a flat list.", param_options: {}}
    col_stats:     {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Compute count/sum/avg/min/max for a numeric column. Returns a record.", param_options: {}}
    summarize:     {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Multi-column aggregate: --cols 'a b' --ops 'avg sum'. Returns a record of col_op keys."
                   param_options: {ops: ["avg", "sum", "min", "max", "count"]}}
    null_fill:     {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Fill null values in a table column with a NUON constant or forward-fill."
                   param_options: {op: ["const", "ffill"]}}
    group_agg:     {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Aggregate a group_by record into a [{group, value}] summary table."
                   param_options: {op: ["avg", "sum", "min", "max", "count", "first"]}}
    transpose:     {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Transpose a table (rows become columns) or convert a record to a [{column, value}] table.", param_options: {}}
    values:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Extract the values of a record as a list (complement to columns).", param_options: {}}
    columns:       {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Extract the column names of a table or record as a list.", param_options: {}}
    zip:           {category: "transform", color: "#3b82f6", wirable: ["right"],        agent_hint: "Zip two parallel lists into a table of records. Wire second list to --right port. --key_a / --key_b name the fields.", param_options: {}}
    batch:         {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Split a list into chunks of --size elements. Returns a list of lists.", param_options: {}}
    window:        {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Rolling N-row window aggregate over a table column. Adds a rolling result column."
                   param_options: {op: ["avg", "sum", "min", "max"]}}
    items:         {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Convert a record to a [{key, value}] table — complement to columns.", param_options: {}}
    find:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Find the index of the first list element matching a condition ($in = element).", param_options: {}}
    row:           {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Get a row at a specific index from a table.", param_options: {}}
    move:          {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Move a column to a new position in a table. Use --before to insert before another column.", param_options: {}}
    chunk_by:      {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Group consecutive list elements by a predicate — splits when value changes.", param_options: {}}
    match:         {category: "logic",     color: "#ec4899", wirable: [],               agent_hint: "Multi-way conditional: match a value against patterns. Patterns separated by spaces, each pattern:result pair colon-delimited."
                   param_options: {}}
    try:           {category: "logic",     color: "#ec4899", wirable: [],               agent_hint: "Try an expression, return fallback NUON on error.", param_options: {}}
    catch:         {category: "logic",     color: "#ec4899", wirable: [],               agent_hint: "Catch errors and handle them with a handler expression.", param_options: {}}
    for:           {category: "logic",     color: "#ec4899", wirable: [],               agent_hint: "Iterate over a list, accumulate results. $in = current element, $acc built up in --init accumulator.", param_options: {}}
    while:         {category: "logic",     color: "#ec4899", wirable: [],               agent_hint: "While loop with condition and body expressions. --max-iter prevents infinite loops.", param_options: {}}
    display:       {category: "output",    color: "#22c55e", wirable: [],               agent_hint: "Display the value (writes to stderr) and pass it through — safe to use mid-pipeline.", param_options: {}}
    file_out:      {category: "output",    color: "#22c55e", wirable: [],               agent_hint: "Write the value to a file. format: json, csv, text, or nuon"
                   param_options: {format: ["json", "csv", "text", "nuon"]}}
    return:        {category: "output",    color: "#22c55e", wirable: [],               agent_hint: "Return the pipeline result as the final output (pass-through terminal node)", param_options: {}}
    llm:           {category: "external",  color: "#a855f7", wirable: ["context"],
                   agent_hint: "Call an LLM. Config via server env: LLM_ENDPOINT (empty=Anthropic cloud, set for OpenAI-compatible/local), LLM_API_KEY, LLM_MODEL (default model ID — node param overrides when set). The context param is sent as a system prompt (not prepended to user message, so it is not echoed back)."
                   param_options: {}}
    analyze:       {category: "external",  color: "#a855f7", wirable: [],
                   agent_hint: "Send a table to an LLM for analysis. Formats rows as numbered items [1]..[N] so the model can cite sources by number. --fields selects which columns to include (comma-sep; default: all except noise cols). --prompt sets the task. Returns a string."
                   param_options: {}}
    http_post:     {category: "external",  color: "#a855f7", wirable: [],               agent_hint: "HTTP POST request — pipe body in, get response back", param_options: {}}
    http_put:      {category: "external",  color: "#a855f7", wirable: [],               agent_hint: "HTTP PUT request — pipe body in, get response back", param_options: {}}
    http_delete:   {category: "external",  color: "#a855f7", wirable: [],               agent_hint: "HTTP DELETE request", param_options: {}}
    http_patch:    {category: "external",  color: "#a855f7", wirable: [],               agent_hint: "HTTP PATCH request — pipe body in, get response back", param_options: {}}
    http_head:     {category: "external",  color: "#a855f7", wirable: [],               agent_hint: "HTTP HEAD request — returns headers only", param_options: {}}
    hash:          {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Compute hash of a string: md5, sha256", param_options: {algo: ["md5", "sha256"]}}
    encode_base64: {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Encode a string to base64", param_options: {}}
    decode_base64: {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Decode a base64 string to plain text", param_options: {}}
    encode_hex:    {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Encode a string to hex", param_options: {}}
    decode_hex:    {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Decode a hex string to plain text", param_options: {}}
    math:          {category: "compute",   color: "#eab308", wirable: ["operand"],      agent_hint: "Apply a math operation (+, -, *, /) to a number. Wire a number to --operand for multi-input."
                   param_options: {op: ["+", "-", "*", "/"]}}
    string_op:     {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Apply a string operation: upcase, downcase, trim, length, split, replace, starts-with, ends-with, contains, substring (arg: old:new)"
                   param_options: {op: ["upcase", "downcase", "trim", "length", "split", "replace", "starts-with", "ends-with", "contains", "substring"]}}
    compact:       {category: "transform", color: "#3b82f6", wirable: [],               agent_hint: "Remove null values from a list or table", param_options: {}}
    glob:          {category: "file",      color: "#f97316", wirable: [],               agent_hint: "Find files matching a glob pattern (e.g. **/*.json)", param_options: {}}
    path_parse:     {category: "file",      color: "#f97316", wirable: [],               agent_hint: "Parse a file path into its components (dir, stem, extension)", param_options: {}}
    path_join:     {category: "file",      color: "#f97316", wirable: [],               agent_hint: "Join path components into a full path", param_options: {}}
    type_cast:     {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Cast a value to a target type: int, float, string, bool"
                   param_options: {target: ["int", "float", "string", "bool"]}}
    math_fn:       {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Apply a math function: round/floor/ceil/abs on a number, or sum/min/max/avg/sqrt/median/stddev on a list or table column"
                   param_options: {op: ["round", "floor", "ceil", "abs", "sum", "min", "max", "avg", "sqrt", "median", "stddev"]}}
    each:          {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Apply a Nu expression to every element of a list. Use $in for the current element. e.g. $in * 2", param_options: {}}
    str_concat:    {category: "compute",   color: "#eab308", wirable: ["prefix", "suffix"], agent_hint: "Concatenate strings: prepend --prefix and/or append --suffix. Both ports are wirable. Param values are plain strings — do NOT use NUON quoting (set prefix to label= not \\\"label=\\\").", param_options: {}}
    str_interp:    {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Template string interpolation — input must be a record; use {field} placeholders in --template", param_options: {}}
    url_encode:    {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Percent-encode a string for safe use in a URL", param_options: {}}
    url_decode:    {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Decode a percent-encoded URL string", param_options: {}}
    to_json:       {category: "output",    color: "#22c55e", wirable: [], agent_hint: "Serialize any value to a JSON string", param_options: {}}
    to_csv:        {category: "output",    color: "#22c55e", wirable: [], agent_hint: "Serialize a table to a CSV string", param_options: {}}
    to_text:       {category: "output",    color: "#22c55e", wirable: [], agent_hint: "Convert any value to a plain text string (into string)", param_options: {}}
    to_nuon:       {category: "output",    color: "#22c55e", wirable: [], agent_hint: "Serialize any value to a NUON string (Nu's native format)", param_options: {}}
    from_string:   {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Parse a string as JSON, NUON, CSV, TOML, or YAML into a value"
                   param_options: {format: ["json", "nuon", "csv", "toml", "yaml"]}}
    row_apply:     {category: "compute",   color: "#eab308", wirable: [],               agent_hint: "Apply a Nu expression to each table row ($in = row record). --as_col adds result as new column; omit to replace the row. IMPORTANT: when using --as_col, the expression must return a scalar (string/number/bool) — returning the whole row record creates a nested column that breaks downstream filter comparisons.", param_options: {}}
    date_format:   {category: "datetime",  color: "#06b6d4", wirable: [],               agent_hint: "Format a datetime as a string using a strftime pattern (default: %Y-%m-%d %H:%M:%S)", param_options: {}}
    into_datetime: {category: "datetime",  color: "#06b6d4", wirable: [],               agent_hint: "Parse a string into a datetime value — optionally provide a --fmt strftime pattern", param_options: {}}
    if:            {category: "logic",     color: "#ec4899", wirable: [],               agent_hint: "Conditional gate: pass input through if condition is true, else return --fallback NUON value"
                   param_options: {op: ["==", "!=", ">", "<", "is-empty", "is-not-empty"]}}
    # NOTE: conditional routing (if/else branching to different downstream nodes) is a
    # known gap — deferred. Requires graph-level routing, not a single primitive.
}

# ── Input primitives ──────────────────────────────────────────────────────────

# Fetch data from a URL via HTTP GET
export def "prim-fetch" [
    --url: string = ""           # URL to fetch
    --headers: string = "{}"     # Headers as NUON record string
]: nothing -> any {
    let h = ($headers | from nuon)
    if ($h | is-empty) {
        http get $url
    } else {
        http get $url --headers $h
    }
}

# Provide a fixed constant value. Accepts NUON expressions (42, [1 2 3], {a: 1}) or plain strings.
export def "prim-const" [
    --value: string = "null"     # Value to emit: NUON expression or plain string
]: nothing -> any {
    try { $value | from nuon } catch { $value }
}

# Read an environment variable
export def "prim-env" [
    --key: string = ""           # Environment variable name
]: nothing -> string {
    $env | get $key
}

# Read a file (auto-detects format)
export def "prim-file-in" [
    --path: string = ""          # File path to read
]: nothing -> any {
    open $path
}

# ── Transform primitives ──────────────────────────────────────────────────────

# Filter table rows by column comparison
export def "prim-filter" [
    --column: string = ""        # Column name to filter on
    --op: string = "=="          # Operator: >, <, ==, !=, contains
    --value: string = ""         # Comparison value
]: table -> table {
    match $op {
        ">" => { where {|r| ($r | get $column) > ($value | into float) } }
        "<" => { where {|r| ($r | get $column) < ($value | into float) } }
        "==" => { where {|r| ($r | get $column | into string) == $value } }
        "!=" => { where {|r| ($r | get $column | into string) != $value } }
        "contains" => { where {|r| ($r | get $column | into string | str contains $value) } }
        _ => { error make {msg: $"Unknown filter op: ($op). Valid: >, <, ==, !=, contains"} }
    }
}

# Add or replace a column with a NUON constant value
export def "prim-map" [
    --column: string = ""        # Column name to add or update
    --value: string = "null"     # NUON literal for the new value
]: table -> table {
    upsert $column {|_| $value | from nuon}
}

# Keep only the specified columns
export def "prim-select" [
    --columns: string = ""       # Space-separated column names (e.g. "name age email")
]: table -> table {
    select ...($columns | split row " " | where {|c| $c != ""})
}

# Sort a table by a column
export def "prim-sort" [
    --column: string = ""        # Column to sort by
    --direction: string = "asc"  # Sort direction: asc or desc
]: table -> table {
    if $direction == "desc" {
        sort-by {|r| $r | get $column} --reverse
    } else {
        sort-by {|r| $r | get $column}
    }
}

# ── Output primitives ─────────────────────────────────────────────────────────

# Display value (writes to stderr so it doesn't corrupt NUON output) and passes input through
export def "prim-display" []: any -> any {
    print --stderr ($in | table)
    $in
}

# Write value to a file
export def "prim-file-out" [
    --path: string = ""          # File path to write to
    --format: string = "json"    # Output format: json, csv, text, nuon
]: any -> record {
    match $format {
        "json" => { $in | to json | save --force $path }
        "csv" => { $in | to csv | save --force $path }
        "text" => { $in | into string | save --force $path }
        _ => { $in | to nuon | save --force $path }
    }
    {saved: $path, format: $format}
}

# Return the pipeline result (pass-through terminal node)
export def "prim-return" []: any -> any {
    $in
}

# ── External primitives ───────────────────────────────────────────────────────

# Call an LLM. Config via server env vars:
#   LLM_ENDPOINT — if unset/empty, uses Anthropic cloud; otherwise OpenAI-compatible (LM Studio, etc.)
#   LLM_API_KEY  — Bearer token; falls back to ANTHROPIC_API_KEY for Anthropic; omit for LM Studio
#   LLM_MODEL    — default model ID; node --model param overrides when set
export def "prim-llm" [
    --model:      string = ""    # Model ID — overrides LLM_MODEL env var when set
    --context:    string = ""    # System prompt sent as system role (not prepended to user message)
    --max_tokens: string = "1024"  # Max tokens to generate
]: string -> string {
    let llm_endpoint = (try { $env.LLM_ENDPOINT } catch { "" })
    let use_anthropic = ($llm_endpoint | is-empty)
    let url = if $use_anthropic { "https://api.anthropic.com/v1/messages" } else { $llm_endpoint }
    let api_key = if $use_anthropic {
        try { $env.LLM_API_KEY } catch { try { $env.ANTHROPIC_API_KEY } catch { "" } }
    } else {
        try { $env.LLM_API_KEY } catch { "" }
    }
    let resolved_model = if ($model | is-empty) {
        try { $env.LLM_MODEL } catch { if $use_anthropic { "claude-haiku-4-5-20251001" } else { "" } }
    } else { $model }

    if $use_anthropic and ($api_key | is-empty) {
        error make {msg: "llm: no API key — set LLM_API_KEY or ANTHROPIC_API_KEY in server env. For a local model, set LLM_ENDPOINT to an OpenAI-compatible URL (e.g. http://host.docker.internal:1234/v1/chat/completions for LM Studio)."}
    }

    let input = $in
    let max_tok = ($max_tokens | into int)

    if $use_anthropic {
        # Anthropic uses a top-level `system` field, not a system role in messages
        let body = if ($context | is-empty) {
            {model: $resolved_model, max_tokens: $max_tok, messages: [{role: "user", content: $input}]}
        } else {
            {model: $resolved_model, max_tokens: $max_tok, system: $context, messages: [{role: "user", content: $input}]}
        }
        let resp = (http post $url
            --headers {x-api-key: $api_key, anthropic-version: "2023-06-01", content-type: "application/json"}
            ($body | to json))
        $resp | get content.0.text
    } else {
        # OpenAI-compatible: context becomes a system role message
        let messages = if ($context | is-empty) {
            [{role: "user", content: $input}]
        } else {
            [{role: "system", content: $context}, {role: "user", content: $input}]
        }
        let body = {model: $resolved_model, max_tokens: $max_tok, messages: $messages}
        let headers = if ($api_key | is-empty) {
            {content-type: "application/json"}
        } else {
            {Authorization: $"Bearer ($api_key)", content-type: "application/json"}
        }
        let resp = (http post $url --headers $headers ($body | to json))
        let msg = ($resp | get choices.0.message)
        let content = (try { $msg | get content | default "" } catch { "" })
        if ($content | is-empty) {
            # Reasoning models (Gemma, DeepSeek-R1, QwQ, etc.) put answer in reasoning_content
            try { $msg | get reasoning_content | default "" } catch { "" }
        } else {
            $content
        }
    }
}

# Send a table to an LLM for analysis, with rows formatted as numbered citations
export def "prim-analyze" [
    --prompt:     string = "Summarize the key themes. For each theme cite the source items by number (e.g. [3], [7])."
    --fields:     string = ""      # Comma-separated columns to include (default: all except noise)
    --context:    string = "You are a concise analyst. Output only your final answer — no thinking, no self-correction, no preamble."  # System prompt
    --model:      string = ""      # Model ID — overrides LLM_MODEL env var when set
    --max_tokens: string = "2048"  # Max tokens to generate
]: table -> string {
    let tbl = $in

    # Noise columns added by source nodes that clutter LLM context
    let noise = ["permalink", "created_utc", "upvote_ratio", "objectID", "story_id"]

    # Determine which columns to use
    let all_cols = ($tbl | columns)
    let use_cols = if ($fields | is-empty) {
        $all_cols | where {|c| not ($noise | any {|n| $n == $c})}
    } else {
        $fields | split row "," | each {|c| $c | str trim} | where {|c| $c != ""}
    }

    # Format as numbered rows for citation
    let formatted = ($tbl | enumerate | each {|row|
        let n    = ($row.index + 1)
        let item = ($row.item)
        let parts = ($use_cols | each {|col|
            let v = (try { $item | get $col | into string } catch { "" })
            $"($col): ($v)"
        })
        $"[($n)] ($parts | str join '  ')"
    } | str join "\n")

    let user_msg = $"($prompt)\n\n($formatted)"

    # Resolve LLM config (same logic as prim-llm)
    let llm_endpoint = (try { $env.LLM_ENDPOINT } catch { "" })
    let use_anthropic = ($llm_endpoint | is-empty)
    let url = if $use_anthropic { "https://api.anthropic.com/v1/messages" } else { $llm_endpoint }
    let api_key = if $use_anthropic {
        try { $env.LLM_API_KEY } catch { try { $env.ANTHROPIC_API_KEY } catch { "" } }
    } else {
        try { $env.LLM_API_KEY } catch { "" }
    }
    let resolved_model = if ($model | is-empty) {
        try { $env.LLM_MODEL } catch { if $use_anthropic { "claude-haiku-4-5-20251001" } else { "" } }
    } else { $model }

    if $use_anthropic and ($api_key | is-empty) {
        error make {msg: "analyze: no API key — set LLM_API_KEY or ANTHROPIC_API_KEY"}
    }

    let max_tok = ($max_tokens | into int)

    if $use_anthropic {
        let body = if ($context | is-empty) {
            {model: $resolved_model, max_tokens: $max_tok, messages: [{role: "user", content: $user_msg}]}
        } else {
            {model: $resolved_model, max_tokens: $max_tok, system: $context, messages: [{role: "user", content: $user_msg}]}
        }
        let resp = (http post $url
            --headers {x-api-key: $api_key, anthropic-version: "2023-06-01", content-type: "application/json"}
            ($body | to json))
        $resp | get content.0.text
    } else {
        let messages = if ($context | is-empty) {
            [{role: "user", content: $user_msg}]
        } else {
            [{role: "system", content: $context}, {role: "user", content: $user_msg}]
        }
        let body = {model: $resolved_model, max_tokens: $max_tok, messages: $messages}
        let headers = if ($api_key | is-empty) {
            {content-type: "application/json"}
        } else {
            {Authorization: $"Bearer ($api_key)", content-type: "application/json"}
        }
        let resp = (http post $url --headers $headers ($body | to json))
        let msg = ($resp | get choices.0.message)
        let content = (try { $msg | get content | default "" } catch { "" })
        if ($content | is-empty) {
            try { $msg | get reasoning_content | default "" } catch { "" }
        } else {
            $content
        }
    }
}

# ── Compute primitives ────────────────────────────────────────────────────────

# Apply a math operation to a number
export def "prim-math" [
    --op: string = "+"           # Operation: +, -, *, /
    --operand: string = "0"      # The second operand (as string, parsed to float)
]: number -> number {
    let x = $in
    let operands = if (($operand | from json | describe) | str starts-with 'list') {
        ($operand | from json | each {|v| $v | into float })
    } else {
        [($operand | into float)]
    }
    $operands | reduce --fold $x {|n, acc|
        match $op {
            "+" => { $acc + $n }
            "-" => { $acc - $n }
            "*" => { $acc * $n }
            "/" => { $acc / $n }
            _ => { error make {msg: $"Unknown math op: ($op). Valid: +, -, *, /"} }
        }
    }
}

# Apply a string operation
export def "prim-string-op" [
    --op: string = "upcase"      # Operation: upcase, downcase, trim, length, split, replace, starts-with, ends-with, contains, substring
    --arg: string = ""           # Arg for split (delimiter), replace (old:new), starts-with/ends-with/contains (needle), substring (start:end)
]: string -> any {
    let s = $in
    match $op {
        "upcase" => { $s | str upcase }
        "downcase" => { $s | str downcase }
        "trim" => { $s | str trim }
        "length" => { $s | str length }
        "split" => { $s | split row $arg }
        "replace" => {
            let parts = ($arg | split row ":" | first 2)
            $s | str replace ($parts | get 0) ($parts | get 1)
        }
        "starts-with" => { $s | str starts-with $arg }
        "ends-with" => { $s | str ends-with $arg }
        "contains" => { $s | str contains $arg }
        "substring" => {
            let parts = ($arg | split row ":" | each {|x| $x | into int })
            $s | str substring ($parts | get 0)..<($parts | get 1)
        }
        _ => { error make {msg: $"Unknown string op: ($op). Valid: upcase, downcase, trim, length, split, replace, starts-with, ends-with, contains, substring"} }
    }
}

# Cast a value to a target type
export def "prim-type-cast" [
    --target: string = "string"  # Target type: int, float, string, bool
]: any -> any {
    let v = $in
    match $target {
        "int" => { $v | into int }
        "float" => { $v | into float }
        "string" => { $v | into string }
        "bool" => { $v | into bool }
        _ => { error make {msg: $"Unknown type: ($target). Valid: int, float, string, bool"} }
    }
}

# ── Additional transform primitives ──────────────────────────────────────────

# Count the number of rows in a table
export def "prim-count" []: table -> int {
    $in | length
}

# Return the first N rows of a table
export def "prim-first" [
    --n: string = "10"             # Number of rows to return
]: table -> table {
    $in | first ($n | into int)
}

# Return the last N rows of a table
export def "prim-last" [
    --n: string = "10"             # Number of rows to return
]: table -> table {
    $in | last ($n | into int)
}

# Rename a column
export def "prim-rename" [
    --from: string = ""            # Current column name
    --to: string = ""              # New column name
]: table -> table {
    $in | rename --column {($from): $to}
}

# Get a field from a record or an index from a list
export def "prim-get" [
    --key: string = ""             # Field name (record) or 0-based integer index (list)
]: any -> any {
    let v = $in
    if ($v | describe | str starts-with 'list') {
        $v | get ($key | into int)
    } else {
        $v | get $key
    }
}

# ── Additional external primitives ────────────────────────────────────────────

# HTTP POST request — pipe body, specify URL
export def "prim-http-post" [
    --url: string = ""             # URL to POST to
    --content-type: string = "application/json"  # Content-Type header
]: any -> any {
    $in | to json | http post $url --content-type $content_type
}

# ── Additional compute primitives ─────────────────────────────────────────────

# Format a value as a string (json, nuon, csv, or text)
export def "prim-to-json" []: any -> string { $in | to json }
export def "prim-to-csv"  []: any -> string { $in | to csv }
export def "prim-to-text" []: any -> string { $in | into string }
export def "prim-to-nuon" []: any -> string { $in | to nuon }

# Parse a string as json, nuon, csv, toml, or yaml
export def "prim-from-string" [
    --format: string = "json"      # Input format: json, nuon, csv, toml, yaml
]: string -> any {
    match $format {
        "csv" => { $in | from csv }
        "nuon" => { $in | from nuon }
        "toml" => { $in | from toml }
        "yaml" => { $in | from yaml }
        _ => { $in | from json }
    }
}

# ── File operation primitives ─────────────────────────────────────────────────

# List directory contents as a table
export def "prim-ls" [
    --path: string = "."             # Directory path to list
]: nothing -> table {
    ls $path
}

# Remove a file
export def "prim-rm" [
    --path: string = ""              # File path to remove
]: nothing -> nothing {
    rm $path
}

# Create a directory (and any missing parents)
export def "prim-mkdir" [
    --path: string = ""              # Directory path to create
]: nothing -> nothing {
    mkdir $path
}

# Find files matching a glob pattern
export def "prim-glob" [
    --pattern: string = ""          # Glob pattern (e.g. **/*.json, *.txt)
]: nothing -> list {
    glob $pattern
}

# Parse a file path into its components
export def "prim-path-parse" [
]: string -> record {
    let p = $in
    let abs = ($p | path expand)
    let parsed = ($abs | path parse)
    {
        full: $abs
        dir: ($parsed | get parent)
        stem: ($parsed | get stem)
        extension: ($parsed | get extension)
    }
}

# Join path components into a full path
export def "prim-path-join" [
    --parts: string = ""            # Space-separated path components to join
]: string -> string {
    let base = $in
    let components = ($parts | split row " " | where {|c| $c != ""})
    $base | path join ...$components
}

# ── Record / object operation primitives ─────────────────────────────────────

# Merge a NUON record into the input record
export def "prim-merge" [
    --with: string = "{}"            # NUON record to merge in (overlapping keys overwritten)
]: record -> record {
    let overlay = if (($with | from json | describe) | str starts-with 'list') {
        ($with | from json | each {|v| $v | from nuon} | reduce {|item, acc| $acc | merge $item })
    } else {
        ($with | from nuon)
    }
    $in | merge $overlay
}

# Remove named columns from a table or record
export def "prim-reject" [
    --columns: string = ""           # Space-separated column names to remove
]: any -> any {
    reject ...($columns | split row " " | where {|c| $c != ""})
}

# Update a field with a NUON value
export def "prim-update" [
    --field: string = ""             # Field name to update
    --value: string = "null"         # NUON replacement value
]: any -> any {
    update $field ($value | from nuon)
}

# ── Additional collection operation primitives ────────────────────────────────

# Group table rows by a column — returns a record keyed by column values
export def "prim-group-by" [
    --column: string = ""            # Column to group by
]: table -> record {
    $in | group-by {|x| $x | get $column}
}

# Reduce a list to a single value
export def "prim-reduce" [
    --op: string = "sum"             # Operation: sum, product, min, max, avg, join
    --sep: string = ", "             # Separator (join only)
]: list -> any {
    match $op {
        "sum"     => { $in | math sum }
        "product" => { $in | math product }
        "min"     => { $in | math min }
        "max"     => { $in | math max }
        "avg"     => { $in | math avg }
        "join"    => { $in | str join $sep }
        _ => { error make {msg: $"Unknown reduce op: ($op). Valid: sum, product, min, max, avg, join"} }
    }
}

# Return unique (deduplicated) values from a list
export def "prim-uniq" []: list -> list {
    $in | uniq
}

# ── Extended math primitives ──────────────────────────────────────────────────

# Apply a math function to a number, list, or table column
export def "prim-math-fn" [
    --op: string = "round"           # Operation: round, floor, ceil, abs, sum, min, max, avg
    --column: string = ""            # Column name (for table input — extracts column first)
]: any -> any {
    let data = if ($column | is-not-empty) { $in | get $column } else { $in }
    match $op {
        "round" => { $data | math round }
        "floor" => { $data | math floor }
        "ceil"  => { $data | math ceil }
        "abs"   => { $data | math abs }
        "sum"   => { $data | math sum }
        "min"   => { $data | math min }
        "max"   => { $data | math max }
        "avg"   => { $data | math avg }
        "sqrt"  => { $data | math sqrt }
        "median" => { $data | math median }
        "stddev" => { $data | math stddev }
        _ => { error make {msg: $"Unknown math fn: ($op). Valid: round, floor, ceil, abs, sum, min, max, avg, sqrt, median, stddev"} }
    }
}

# ── Date / time primitives ────────────────────────────────────────────────────

# Return the current date and time
export def "prim-date-now" []: nothing -> datetime {
    date now
}

# Format a datetime as a string
export def "prim-date-format" [
    --fmt: string = "%Y-%m-%d %H:%M:%S"  # strftime format string
]: datetime -> string {
    $in | format date $fmt
}

# Parse a string into a datetime value
export def "prim-into-datetime" [
    --fmt: string = ""               # Optional strftime format hint
]: string -> datetime {
    if ($fmt | is-empty) {
        $in | into datetime
    } else {
        $in | into datetime --format $fmt
    }
}

# Add a duration to a datetime
export def "prim-date-add" [
    --amount: string = "1day"        # Duration string: 1day, 2hr, 30min, -7day, etc.
]: datetime -> datetime {
    $in + ($amount | into duration)
}

# ── Logic primitives ──────────────────────────────────────────────────────────

# Conditional gate: pass input through if condition is true, else return fallback
export def "prim-if" [
    --column: string = ""            # Field to test (empty = test the whole input value)
    --op: string = "=="              # Operator: ==, !=, >, <, is-empty, is-not-empty
    --value: string = ""             # Comparison value (not used for is-empty / is-not-empty)
    --fallback: string = "null"      # NUON value returned when condition is false
]: any -> any {
    let v = $in
    let subject = if ($column | is-not-empty) { $v | get $column } else { $v }
    let passes = match $op {
        "=="          => { ($subject | into string) == $value }
        "!="          => { ($subject | into string) != $value }
        ">"           => { ($subject | into float) > ($value | into float) }
        "<"           => { ($subject | into float) < ($value | into float) }
        "is-empty"    => { $subject | is-empty }
        "is-not-empty" => { not ($subject | is-empty) }
        _ => { error make {msg: $"Unknown op: ($op). Valid: ==, !=, >, <, is-empty, is-not-empty"} }
    }
    if $passes { $v } else { $fallback | from nuon }
}

# ── Each / loop primitive ─────────────────────────────────────────────────────

# Apply a Nu expression to every element of a list ($in = current element)
export def "prim-each" [
    --expr: string = "$in"           # Nu expression — use $in for the current element (e.g. $in * 2)
]: list -> list {
    $in | each {|it|
        nu -c $"(($it | to nuon)) | do { ($expr) } | to nuon"
        | from nuon
    }
}

# ── String primitives ─────────────────────────────────────────────────────────

# Concatenate strings — prepend prefix and/or append suffix
export def "prim-str-concat" [
    --prefix: string = ""            # String to prepend (or wire an edge to this port)
    --suffix: string = ""            # String to append  (or wire an edge to this port)
]: string -> string {
    let prefix_val = if (($prefix | from json | describe) | str starts-with 'list') {
        (($prefix | from json) | str join)
    } else {
        $prefix
    }
    let suffix_val = if (($suffix | from json | describe) | str starts-with 'list') {
        (($suffix | from json) | str join)
    } else {
        $suffix
    }
    $"($prefix_val)($in)($suffix_val)"
}

# Template string interpolation — replace {field} placeholders from a record
export def "prim-str-interp" [
    --template: string = ""          # Template with {field} placeholders e.g. "Hello {name}!"
]: record -> string {
    let rec = $in
    mut result = $template
    for key in ($rec | columns) {
        let placeholder = ("{" + $key + "}")
        let val = $"($rec | get $key)"
        $result = ($result | str replace --all $placeholder $val)
    }
    $result
}

# Percent-encode a string for safe use in a URL
export def "prim-url-encode" []: string -> string {
    $in | url encode
}

# Decode a percent-encoded URL string
export def "prim-url-decode" []: string -> string {
    $in | url decode
}

# ── List primitives ───────────────────────────────────────────────────────────

# Append a NUON list or single value to the input list
export def "prim-append" [
    --items: string = "[]"           # NUON list or value to append (wire an edge to this port for multi-input)
]: any -> list {
    let input = $in
    let parsed = if (($items | from json | describe) | str starts-with 'list') {
        ($items | from json | each {|v| $v | from nuon} | flatten)
    } else {
        ($items | from nuon)
    }
    let desc = ($parsed | describe)
    if ($desc | str starts-with 'list') or ($desc | str starts-with 'table') {
        $input | append $parsed
    } else {
        $input | append [$parsed]
    }
}

# Flatten one level of nesting from a list of lists
export def "prim-flatten" []: list -> list {
    $in | flatten
}

# Reverse a list or table
export def "prim-reverse" []: any -> any {
    $in | reverse
}

# Remove null values from a list or table
export def "prim-compact" []: any -> any {
    $in | compact
}

# Skip the first N rows/elements
export def "prim-drop" [
    --n: string = "1"                # Number of rows/elements to skip
]: any -> any {
    $in | skip ($n | into int)
}

# Add a zero-based index to each element — returns [{index, value}, ...]
export def "prim-enumerate" []: any -> table {
    $in | enumerate | each {|it| {index: $it.index, value: $it.item}}
}

# Wrap a single value into a one-element list
export def "prim-wrap" []: any -> list {
    [$in]
}

# ── Join primitive (multi-input) ──────────────────────────────────────────────

# SQL-style join two tables on a shared column
# Wire a second table to the --right port to use as a multi-input node
export def "prim-join" [
    --right: string = "[]"           # Right table as NUON (wire an edge to this port)
    --on: string = ""                # Column name to join on
    --type: string = "inner"         # Join type: inner or left
]: table -> table {
    let r = if (($right | from json | describe) | str starts-with 'list') {
        let tables = ($right | from json | each {|v| $v | from nuon})
        if ($tables | length) > 0 { $tables | get 0 } else { [] | table }
    } else {
        let parsed = ($right | from nuon)
        if ($parsed | describe | str starts-with 'record') {
            [$parsed] | table
        } else {
            $parsed
        }
    }
    if $type == "left" {
        $in | join $r $on --left
    } else {
        $in | join $r $on
    }
}

# ── Multi-source table primitives ─────────────────────────────────────────────

# Vertically stack two tables (UNION ALL equivalent)
# Wire a second table to the --more port for multi-input use
export def "prim-table-concat" [
    --more: string = "[]"            # Second table as NUON (wire an edge to this port)
]: table -> table {
    let extra = if (($more | from json | describe) | str starts-with 'list') {
        let tables = ($more | from json | each {|v| $v | from nuon})
        $tables | flatten
    } else {
        ($more | from nuon)
    }
    $in | append $extra
}

# Append a record as a new row to a table
# Wire a record source to the --row port for multi-input use
export def "prim-insert-row" [
    --row: string = "{}"             # Record to append as NUON (wire an edge to this port)
]: table -> table {
    let r = ($row | from nuon)
    $in | append [$r]
}

# ── Column-level primitives ───────────────────────────────────────────────────

# Extract a single column from a table as a flat list
export def "prim-col-to-list" [
    --column: string = ""            # Column name to extract
]: table -> list {
    $in | get $column
}

# Compute summary statistics for a numeric column — returns a record
export def "prim-col-stats" [
    --column: string = ""            # Column to compute stats on
]: table -> record {
    let col = ($in | get $column)
    {
        count: ($col | length)
        sum:   ($col | math sum)
        avg:   ($col | math avg)
        min:   ($col | math min)
        max:   ($col | math max)
    }
}

# Multi-column aggregate — returns a flat record with {col_op: value} keys
# --cols and --ops are parallel space-separated lists (e.g. "price volume", "avg sum")
export def "prim-summarize" [
    --cols: string = ""              # Space-separated column names (e.g. "price volume")
    --ops: string = ""               # Space-separated ops per column (avg sum min max count)
]: table -> record {
    let tbl = $in
    let col_list = ($cols | split row " " | where {|c| $c != ""})
    let op_list  = ($ops  | split row " " | where {|o| $o != ""})
    mut result = {}
    for i in 0..<($col_list | length) {
        let col = ($col_list | get $i)
        let op  = ($op_list  | get $i)
        let vals = ($tbl | get $col)
        let v = match $op {
            "avg"   => { $vals | math avg }
            "sum"   => { $vals | math sum }
            "min"   => { $vals | math min }
            "max"   => { $vals | math max }
            "count" => { $vals | length }
            _ => { null }
        }
        $result = ($result | upsert $"($col)_($op)" $v)
    }
    $result
}

# Fill null/empty values in a table column
# op: const (fill with --value) or ffill (forward-fill from previous non-null)
export def "prim-null-fill" [
    --column: string = ""            # Column to fill nulls in
    --op: string = "const"           # Strategy: const or ffill
    --value: string = "null"         # NUON fill value (used when op is const)
]: table -> table {
    let tbl = $in
    let fill = ($value | from nuon)
    if $op == "ffill" {
        $tbl
        | reduce --fold {last: null, rows: []} {|row, acc|
            let v = ($row | get $column)
            let fill_val = if ($v == null) or ($v | is-empty) { $acc.last } else { $v }
            {last: $fill_val, rows: ($acc.rows | append [($row | upsert $column $fill_val)])}
        }
        | get rows
    } else {
        $tbl | upsert $column {|row|
            let v = ($row | get $column)
            if ($v == null) or ($v | is-empty) { $fill } else { $v }
        }
    }
}

# ── Group aggregation ─────────────────────────────────────────────────────────

# Aggregate a group_by record into a [{group, value}] summary table
# Takes the record output of prim-group-by and summarises a column per group
export def "prim-group-agg" [
    --column: string = ""            # Column to aggregate within each group
    --op: string = "avg"             # Aggregation: avg, sum, min, max, count, first
]: record -> table {
    let groups = $in
    $groups | items {|key, rows|
        let vals = ($rows | get $column)
        let v = match $op {
            "sum"   => { $vals | math sum }
            "min"   => { $vals | math min }
            "max"   => { $vals | math max }
            "avg"   => { $vals | math avg }
            "count" => { $vals | length }
            "first" => { $vals | first }
            _ => { null }
        }
        {group: $key, value: $v}
    }
}

# ── Shape / structure primitives ──────────────────────────────────────────────

# Transpose: pivot a table (rows↔columns) or convert a record to [{column, value}]
export def "prim-transpose" []: any -> any {
    $in | transpose
}

# Extract the values of a record as a list (complement to columns)
export def "prim-values" []: record -> list {
    $in | values
}

# Extract the column names of a table or record as a list
export def "prim-columns" []: any -> list {
    $in | columns
}

# ── Parallel-stream primitives ────────────────────────────────────────────────

# Zip two parallel lists into a table of records
# Wire the second list to --right; use --key_a / --key_b to name the fields
export def "prim-zip" [
    --right: string = "[]"           # Right list as NUON (wire an edge to this port)
    --key_a: string = "left"         # Field name for left-side values
    --key_b: string = "right"        # Field name for right-side values
]: list -> table {
    let r = ($right | from nuon)
    $in | zip $r | each {|pair|
        {($key_a): ($pair | get 0), ($key_b): ($pair | get 1)}
    }
}

# ── Chunking / windowing ──────────────────────────────────────────────────────

# Split a list into chunks of --size elements — returns a list of lists
export def "prim-batch" [
    --size: string = "10"            # Number of elements per chunk
]: list -> list {
    $in | chunks ($size | into int)
}

# Rolling N-row window aggregate over a table column — adds a new result column
export def "prim-window" [
    --column: string = ""            # Column to aggregate
    --size: string = "3"             # Window size (number of rows)
    --op: string = "avg"             # Operation: avg, sum, min, max
    --as_col: string = ""            # Output column name (default: rolling_{op}_{column})
]: table -> table {
    let n = ($size | into int)
    let out_col = if ($as_col | is-empty) { $"rolling_($op)_($column)" } else { $as_col }
    let tbl = $in
    let len = ($tbl | length)
    mut rows = []
    for i in 0..<$len {
        let raw = $i - $n + 1
        let start = if $raw < 0 { 0 } else { $raw }
        let window = ($tbl | skip $start | first ($i - $start + 1) | get $column)
        let v = match $op {
            "sum" => { $window | math sum }
            "min" => { $window | math min }
            "max" => { $window | math max }
            _ =>     { $window | math avg }
        }
        $rows = ($rows | append [($tbl | get $i | upsert $out_col $v)])
    }
    $rows
}

# ── Row-wise compute primitive (pandas apply equivalent) ──────────────────────

# Apply a Nu expression to every row of a table ($in = the current row as a record).
# If --as_col is set, the result is added as a new column and the row is preserved.
# If --as_col is empty, the expression must return a record to replace the whole row.
export def "prim-row-apply" [
    --expr: string = "$in"           # Nu expression — $in is the current row (record)
    --as_col: string = ""            # If set, store result here; else expression must return a record
]: table -> table {
    let tbl = $in
    $tbl | each {|row|
        let result = (
            nu -c $"(($row | to nuon)) | do { ($expr) } | to nuon"
            | from nuon
        )
        if ($as_col | is-empty) {
            $result
        } else {
            $row | upsert $as_col $result
        }
    }
}

# ── Record / list introspection primitives ───────────────────────────────────

# Convert a record to a [{key, value}] table (complement to `columns`)
export def "prim-items" []: record -> table {
    $in | items {|key, value| {key: $key, value: $value}}
}

# Find the index of the first element matching a condition
export def "prim-find" [
    --expr: string = "$in"            # Nu expression — $in is current element, should return bool
]: list -> int {
    let list = $in
    let len = ($list | length)
    mut index = -1
    for i in 0..<$len {
        let elem = ($list | get $i)
        let matches = (nu -c $"(($elem | to nuon)) | do { ($expr) } | to nuon" | from nuon)
        if $matches {
            $index = $i
            break
        }
    }
    $index
}

# Get a row at a specific index from a table
export def "prim-row" [
    --index: string = "0"             # 0-based row index to retrieve
]: table -> record {
    $in | get ($index | into int)
}

# Move a column to a new position in a table
export def "prim-move" [
    --column: string = ""             # Column to move
    --before: string = ""             # Insert before this column (empty = move to end)
]: table -> table {
    let input = $in
    let cols = ($input | columns)
    let col_idx = ($cols | enumerate | where $in.item == $column | get 0.index | into int)
    if ($col_idx | is-empty) {
        error make {msg: $"Column not found: ($column)"}
    } else {
        let other_cols = ($cols | where {|c| $c != $column})
        let new_order = if ($before | is-empty) {
            $other_cols | append $column
        } else {
            let before_idx = ($other_cols | enumerate | where $in.item == $before | get 0.index | into int)
            if ($before_idx | is-empty) {
                error make {msg: $"Column not found: ($before)"}
            } else {
                mut result = []
                for i in 0..<($other_cols | length) {
                    if $i == $before_idx {
                        $result = ($result | append $column)
                    }
                    $result = ($result | append ($other_cols | get $i))
                }
                $result
            }
        }
        $input | select ...$new_order
    }
}

# Group consecutive list elements by a predicate
# Returns a list of chunks where the predicate result changes
export def "prim-chunk-by" [
    --expr: string = "$in"            # Nu expression — $in is current element, should return comparable value
]: list -> list {
    $in | chunk-by {|elem|
        nu -c $"(($elem | to nuon)) | do { ($expr) } | to nuon" | from nuon
    }
}

# ── Match / conditional branching ────────────────────────────────────────────

# Multi-way conditional: match a value against patterns and return corresponding result
export def "prim-match" [
    --value: string = ""              # Value to match against (empty = match $in)
    --pattern: string = ""            # Space-separated pattern:result pairs (e.g. "foo:FOO bar:BAR default:DEFAULT")
    --default: string = "null"        # Default result when no pattern matches
]: any -> any {
    let v = if ($value | is-empty) { $in } else { $value }
    let pairs = ($pattern | split row " " | each {|p|
        let parts = ($p | split row ":" | first 2)
        {pattern: ($parts | get 0), result: ($parts | get 1)}
    })
    mut result = null
    mut found = false
    for pair in $pairs {
        if $v == $pair.pattern and not $found {
            $result = (try { $pair.result | from nuon } catch { $pair.result })
            $found = true
        }
    }
    if not $found {
        $result = (try { $default | from nuon } catch { $default })
    }
    $result
}

# ── Error handling primitives ───────────────────────────────────────────────────

# Try executing an expression, return fallback on error
export def "prim-try" [
    --fallback: string = "null"        # NUON value to return on error
    --expr: string = "$in"           # Nu expression to try
]: any -> any {
    try {
        nu -c $"(($in | to nuon)) | do { ($expr) } | to nuon" | from nuon
    } catch {
        $fallback | from nuon
    }
}

# Catch errors from a preceding try with a handler expression
export def "prim-catch" [
    --handler: string = "{}"          # Handler expression that receives the error as $in
    --expr: string = "$in"           # Nu expression that may fail
]: any -> any {
    try {
        nu -c $"(($in | to nuon)) | do { ($expr) } | to nuon" | from nuon
    } catch {|err| 
        nu -c $"(($err | to nuon)) | do { ($handler) } | to nuon" | from nuon
    }
}

# ── Iteration primitives ───────────────────────────────────────────────────────

# For loop: iterate over a list and accumulate results
# Each iteration receives {elem: current_item, acc: accumulator} — expression returns value to append
export def "prim-for" [
    --over: string = "[]"            # List to iterate over (as NUON)
    --init: string = "[]"           # Initial accumulator value
    --expr: string = "$in"          # Nu expression — $in is {elem, acc}, should return value to append
]: any -> any {
    let items = ($over | from nuon)
    mut acc = ($init | from nuon)
    for item in $items {
        let input = {elem: $item, acc: $acc}
        let result = (nu -c $"(($input | to nuon)) | do { ($expr) } | to nuon" | from nuon)
        $acc = ($acc | append $result)
    }
    $acc
}

# While loop: repeat while condition is true
export def "prim-while" [
    --init: string = "{}"            # Initial state value
    --cond: string = "$in"          # Condition expression — should return bool
    --body: string = "$in"          # Body expression — runs each iteration, $in is state
    --max-iter: string = "1000"      # Maximum iterations to prevent infinite loops
]: any -> any {
    mut state = ($init | from nuon)
    let max = ($max_iter | into int)
    mut iter = 0
    while $iter < $max {
        let cond_result = (nu -c $"(($state | to nuon)) | do { ($cond) } | to nuon" | from nuon | into bool)
        if not $cond_result {
            break
        }
        $state = (nu -c $"(($state | to nuon)) | do { ($body) } | to nuon" | from nuon)
        $iter = $iter + 1
    }
    $state
}

# ── Hash / crypto primitives ──────────────────────────────────────────────────

# Compute hash of a string or binary
export def "prim-hash" [
    --algo: string = "sha256"        # Hash algorithm: md5, sha256
]: string -> string {
    match $algo {
        "md5" => { $in | hash md5 }
        "sha256" => { $in | hash sha256 }
        _ => { error make {msg: $"Unknown hash algo: ($algo). Valid: md5, sha256"} }
    }
}

# Encode string to base64
export def "prim-encode-base64" []: string -> string {
    $in | encode base64
}

# Decode base64 to string
export def "prim-decode-base64" []: string -> string {
    $in | decode base64 | decode
}

# Encode string to hex
export def "prim-encode-hex" []: string -> string {
    $in | encode hex
}

# Decode hex to string
export def "prim-decode-hex" []: string -> string {
    $in | decode hex | decode
}

# ── HTTP method primitives ─────────────────────────────────────────────────────

# HTTP PUT request
export def "prim-http-put" [
    --url: string = ""               # URL to PUT to
    --content-type: string = "application/json"  # Content-Type header
]: any -> any {
    $in | to json | http put $url --content-type $content_type
}

# HTTP DELETE request
export def "prim-http-delete" [
    --url: string = ""               # URL to DELETE
]: any -> any {
    http delete $url
}

# HTTP PATCH request
export def "prim-http-patch" [
    --url: string = ""               # URL to PATCH
    --content-type: string = "application/json"  # Content-Type header
]: any -> any {
    $in | to json | http patch $url --content-type $content_type
}

# HTTP HEAD request
export def "prim-http-head" [
    --url: string = ""               # URL to HEAD
]: any -> record {
    http head $url
}

# ── Date / timezone primitives ────────────────────────────────────────────────

# Convert datetime to a different timezone
export def "prim-to-timezone" [
    --zone: string = "UTC"          # Target timezone (e.g. America/New_York, Europe/London)
]: datetime -> datetime {
    $in | date to-timezone $zone
}

# List available timezone names
export def "prim-list-timezone" []: nothing -> list {
    date list-timezone
}

# ── Conversion primitives ─────────────────────────────────────────────────────

# Convert a string into a filesize value (e.g. "5MB" -> 5_000_000 bytes)
export def "prim-into-filesize" []: string -> filesize {
    $in | into filesize
}

# Convert a string into a duration value (e.g. "1hr 30min" -> 90min)
export def "prim-into-duration" []: string -> duration {
    $in | into duration
}
