# GoNude core primitives
# Do not edit this file to add domain-specific nodes — use extensions/ instead.

# Metadata used by scripts/introspect.nu for canvas display and agent use.
# Keys match the short name (strip "prim-", replace "-" with "_").
export const PRIMITIVE_META = {
    fetch: {category: "input", color: "#f97316", agent_hint: "Fetch JSON/table data from a URL via HTTP GET"}
    const: {category: "input", color: "#f97316", agent_hint: "Provide a fixed NUON constant value (e.g. 42, \"hello\", [1 2 3])"}
    env: {category: "input", color: "#f97316", agent_hint: "Read an environment variable by name, returns its string value"}
    file_in: {category: "input", color: "#f97316", agent_hint: "Read a file — auto-detects CSV/JSON/NUON, else returns raw string"}
    filter: {category: "transform", color: "#3b82f6", agent_hint: "Filter table rows: pick column, op (>, <, ==, !=, contains), and value"}
    map: {category: "transform", color: "#3b82f6", agent_hint: "Add or replace a column with a NUON constant value"}
    select: {category: "transform", color: "#3b82f6", agent_hint: "Keep only the named columns from a table (space-separated)"}
    sort: {category: "transform", color: "#3b82f6", agent_hint: "Sort a table by a column. direction: asc or desc"}
    display: {category: "output", color: "#22c55e", agent_hint: "Print the value to stdout — captured in the run log"}
    file_out: {category: "output", color: "#22c55e", agent_hint: "Write the value to a file. format: nuon, json, csv, or text"}
    return: {category: "output", color: "#22c55e", agent_hint: "Return the pipeline result as the final output (pass-through terminal node)"}
    llm: {category: "external", color: "#a855f7", agent_hint: "Call an LLM (Anthropic) with a prompt string. Returns the completion text."}
    math: {category: "compute", color: "#eab308", agent_hint: "Apply a math operation (+, -, *, /) with an operand to a number"}
    string_op: {category: "compute", color: "#eab308", agent_hint: "Apply a string operation: upcase, downcase, trim, length, split, replace (arg: old:new)"}
    type_cast: {category: "compute", color: "#eab308", agent_hint: "Cast a value to a target type: int, float, string, bool"}
}

# ── Input primitives ──────────────────────────────────────────────────────────

# Fetch data from a URL via HTTP GET
export def "prim-fetch" [
    --url: string = ""           # URL to fetch
    --headers: string = "{}"     # Headers as NUON record string
]: nothing -> any {
    let h = ($headers | from nuon)
    if ($h | is-empty) {
        http get $url
    } else {
        http get $url --headers $h
    }
}

# Provide a fixed constant value (NUON expression)
export def "prim-const" [
    --value: string = "null"     # NUON expression (e.g. 42, "hello", [1 2 3])
]: nothing -> any {
    $value | from nuon
}

# Read an environment variable
export def "prim-env" [
    --key: string = ""           # Environment variable name
]: nothing -> string {
    $env | get $key
}

# Read a file (auto-detects format)
export def "prim-file-in" [
    --path: string = ""          # File path to read
]: nothing -> any {
    open $path
}

# ── Transform primitives ──────────────────────────────────────────────────────

# Filter table rows by column comparison
export def "prim-filter" [
    --column: string = ""        # Column name to filter on
    --op: string = "=="          # Operator: >, <, ==, !=, contains
    --value: string = ""         # Comparison value
]: table -> table {
    match $op {
        ">" => { where {|r| ($r | get $column) > ($value | into float) } }
        "<" => { where {|r| ($r | get $column) < ($value | into float) } }
        "==" => { where {|r| ($r | get $column | into string) == $value } }
        "!=" => { where {|r| ($r | get $column | into string) != $value } }
        "contains" => { where {|r| ($r | get $column | into string | str contains $value) } }
        _ => { error make {msg: $"Unknown filter op: ($op). Valid: >, <, ==, !=, contains"} }
    }
}

# Add or replace a column with a NUON constant value
export def "prim-map" [
    --column: string = ""        # Column name to add or update
    --value: string = "null"     # NUON literal for the new value
]: table -> table {
    upsert $column {|_| $value | from nuon}
}

# Keep only the specified columns
export def "prim-select" [
    --columns: string = ""       # Space-separated column names (e.g. "name age email")
]: table -> table {
    select ...($columns | split row " " | where {|c| $c != ""})
}

# Sort a table by a column
export def "prim-sort" [
    --column: string = ""        # Column to sort by
    --direction: string = "asc"  # Sort direction: asc or desc
]: table -> table {
    if $direction == "desc" {
        sort-by {|r| $r | get $column} --reverse
    } else {
        sort-by {|r| $r | get $column}
    }
}

# ── Output primitives ─────────────────────────────────────────────────────────

# Print value to stdout (captured in run log)
export def "prim-display" []: any -> nothing {
    print $in
}

# Write value to a file
export def "prim-file-out" [
    --path: string = ""          # File path to write to
    --format: string = "nuon"    # Output format: nuon, json, csv, text
]: any -> nothing {
    match $format {
        "json" => { $in | to json | save --force $path }
        "csv" => { $in | to csv | save --force $path }
        "text" => { $in | into string | save --force $path }
        _ => { $in | to nuon | save --force $path }
    }
}

# Return the pipeline result (pass-through terminal node)
export def "prim-return" []: any -> any {
    $in
}

# ── External primitives ───────────────────────────────────────────────────────

# Call an LLM (Anthropic Messages API) with a prompt
export def "prim-llm" [
    --model: string = "claude-haiku-4-5-20251001"  # Anthropic model ID
    --context: string = ""                          # Optional system context prepended to prompt
]: string -> string {
    let prompt = if ($context | is-empty) { $in } else { $"($context)\n\n($in)" }
    let body = {
        model: $model
        max_tokens: 1024
        messages: [{role: "user", content: $prompt}]
    }
    let response = (http post "https://api.anthropic.com/v1/messages"
        --headers {
            x-api-key: $env.ANTHROPIC_API_KEY
            anthropic-version: "2023-06-01"
            content-type: "application/json"
        }
        ($body | to json))
    $response | get content.0.text
}

# ── Compute primitives ────────────────────────────────────────────────────────

# Apply a math operation to a number
export def "prim-math" [
    --op: string = "+"           # Operation: +, -, *, /
    --operand: string = "0"      # The second operand (as string, parsed to float)
]: number -> number {
    let x = $in
    let n = ($operand | into float)
    match $op {
        "+" => { $x + $n }
        "-" => { $x - $n }
        "*" => { $x * $n }
        "/" => { $x / $n }
        _ => { error make {msg: $"Unknown math op: ($op). Valid: +, -, *, /"} }
    }
}

# Apply a string operation
export def "prim-string-op" [
    --op: string = "upcase"      # Operation: upcase, downcase, trim, length, split, replace
    --arg: string = ""           # Arg for split (delimiter) or replace (old:new)
]: string -> any {
    let s = $in
    match $op {
        "upcase" => { $s | str upcase }
        "downcase" => { $s | str downcase }
        "trim" => { $s | str trim }
        "length" => { $s | str length }
        "split" => { $s | split row $arg }
        "replace" => {
            let parts = ($arg | split row ":" | first 2)
            $s | str replace ($parts | get 0) ($parts | get 1)
        }
        _ => { error make {msg: $"Unknown string op: ($op). Valid: upcase, downcase, trim, length, split, replace"} }
    }
}

# Cast a value to a target type
export def "prim-type-cast" [
    --target: string = "string"  # Target type: int, float, string, bool
]: any -> any {
    let v = $in
    match $target {
        "int" => { $v | into int }
        "float" => { $v | into float }
        "string" => { $v | into string }
        "bool" => { $v | into bool }
        _ => { error make {msg: $"Unknown type: ($target). Valid: int, float, string, bool"} }
    }
}
